sudo: required
language: java
install: true
jdk: oraclejdk8

services:
    - docker

before_script:
  - bash set-up-test-env.sh
  
script:
  - bash test-script.sh

notifications:
  slack: cleancycle:5lF8hEqYZvrw9XflPC3eG2GD